version: 1
builder:
  configs:
    - scheme: xtool
      platform: macosSpm
      documentation_targets:
      - XTool
    - scheme: xtool
      platform: macosXcodebuild
    # - scheme: xtool
    #   platform: linux
    #   image: # TODO: we need to use our own Docker image for this
    - scheme: XKit
      platform: ios
