overlay: 1.0.0
info:
  title: Overlay for App Store Connect API
  version: 1.0.0
actions:
  - target: '$'
    update:
      components:
        schemas:
          BundleIdCapabilityCreateRequest:
            properties:
              data:
                properties:
                  relationships:
                    properties:
                      capability:
                        type: object
                        properties:
                          data:
                            type: object
                            properties:
                              type:
                                type: string
                                enum: [capabilities]
                              id:
                                "$ref": "#/components/schemas/CapabilityType"
                            required: [id, type]
                        required: [data]
                    required: [capability]
