on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          docker compose run --build --rm supersign -c "swift build --product SupersignCLI"
