on:
  - push
jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        host:
          - runner: ubuntu-24.04
            arch: x86_64
          - runner: ubuntu-24.04-arm
            arch: aarch64
    runs-on: ${{ matrix.host.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          docker compose run --build --rm supersign -c "swift build --product SupersignCLI"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Supersign-${{ matrix.host.arch }}.AppImage
          path: Linux/packages/Supersign.AppImage
  build-macos:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          swift build --product SupersignCLI
